name: Stupid Bot Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
    - run: npm i
    - run: npm test